"""Curated UK-facing catalogue definitions for NutriRoot V0.4.

The nutrient values are generated from FAO/INFOODS WAFCT 2019 profiles by
``build_catalog.py``.  This file contains identity, aliases, cultural coverage,
portion assumptions and transparent baseline recipes; it deliberately contains
no hand-entered nutrient totals.
"""

from __future__ import annotations


WEST_AFRICAN_COUNTRIES = (
    "Benin",
    "Burkina Faso",
    "Cabo Verde",
    "Côte d'Ivoire",
    "Gambia",
    "Ghana",
    "Guinea",
    "Guinea-Bissau",
    "Liberia",
    "Mali",
    "Mauritania",
    "Niger",
    "Nigeria",
    "Senegal",
    "Sierra Leone",
    "Togo",
)


COVERAGE_TIERS = {
    "priority": {
        "countries": ["Nigeria", "Ghana"],
        "reason": (
            "Census 2021 identifies Nigerian and Ghanaian as the two largest "
            "specified West African backgrounds in England and Wales."
        ),
    },
    "extended_uk_communities": {
        "countries": [
            "Sierra Leone",
            "Gambia",
            "Senegal",
            "Côte d'Ivoire",
            "Liberia",
            "Guinea",
        ],
        "reason": "Additional established West African communities and shared food traditions in the UK.",
    },
    "regional": {
        "countries": [
            "Benin",
            "Burkina Faso",
            "Cabo Verde",
            "Guinea-Bissau",
            "Mali",
            "Mauritania",
            "Niger",
            "Togo",
        ],
        "reason": "Broader geographic West African coverage, including foods shared across borders.",
    },
}


def direct(
    key: str,
    name: str,
    profile_code: str,
    aliases: tuple[str, ...],
    countries: tuple[str, ...],
    category: str,
    portion_kind: str,
    note: str = "",
) -> dict:
    return {
        "key": key,
        "name": name,
        "profile_code": profile_code,
        "aliases": aliases,
        "countries": countries,
        "category": category,
        "portion_kind": portion_kind,
        "note": note,
    }


def recipe(
    key: str,
    name: str,
    aliases: tuple[str, ...],
    countries: tuple[str, ...],
    category: str,
    portion_kind: str,
    ingredients: tuple[tuple[str, float, str], ...],
    final_weight_g: float,
    note: str,
) -> dict:
    return {
        "key": key,
        "name": name,
        "aliases": aliases,
        "countries": countries,
        "category": category,
        "portion_kind": portion_kind,
        "ingredients": ingredients,
        "final_weight_g": final_weight_g,
        "note": note,
    }


DIRECT_FOODS = (
    direct(
        "plain_white_rice",
        "White rice, boiled",
        "01_038",
        ("white rice", "plain rice", "boiled rice"),
        WEST_AFRICAN_COUNTRIES,
        "rice and grain staples",
        "rice",
    ),
    direct(
        "brown_rice",
        "Brown rice, boiled",
        "01_035",
        ("brown rice",),
        WEST_AFRICAN_COUNTRIES,
        "rice and grain staples",
        "rice",
    ),
    direct(
        "fonio",
        "Fonio, boiled",
        "01_003",
        ("fonio", "acha"),
        ("Guinea", "Mali", "Senegal", "Burkina Faso", "Nigeria"),
        "rice and grain staples",
        "rice",
    ),
    direct(
        "millet",
        "Pearl millet, boiled",
        "01_033",
        ("boiled millet", "pearl millet"),
        ("Burkina Faso", "Gambia", "Mali", "Mauritania", "Niger", "Senegal"),
        "rice and grain staples",
        "rice",
    ),
    direct(
        "sorghum",
        "Sorghum, boiled",
        "01_042",
        ("boiled sorghum", "sorghum"),
        ("Burkina Faso", "Ghana", "Mali", "Niger", "Nigeria", "Togo"),
        "rice and grain staples",
        "rice",
    ),
    direct(
        "ogi",
        "Ogi / pap, fermented maize porridge",
        "01_100",
        ("ogi", "pap", "akamu", "corn pap", "maize pap"),
        ("Nigeria", "Benin", "Ghana"),
        "breakfasts and porridges",
        "porridge",
    ),
    direct(
        "kenkey",
        "Kenkey, cooked fermented maize dough",
        "01_099",
        ("kenkey", "komi", "dokono"),
        ("Ghana", "Togo", "Benin"),
        "swallows and doughs",
        "swallow",
    ),
    direct(
        "hausa_koko",
        "Hausa koko / ben saalga, fermented millet porridge",
        "01_102",
        ("hausa koko", "koko", "ben saalga", "millet porridge"),
        ("Ghana", "Nigeria", "Burkina Faso"),
        "breakfasts and porridges",
        "porridge",
    ),
    direct(
        "fura_porridge",
        "Fura with milk, fermented millet porridge",
        "01_176",
        ("fura da nono", "fura", "fura with milk"),
        ("Nigeria", "Niger", "Ghana", "Burkina Faso"),
        "breakfasts and porridges",
        "porridge",
        "WAFCT profile is a millet, milk, water and sugar preparation.",
    ),
    direct(
        "instant_noodles",
        "Instant noodles, boiled and drained",
        "01_103",
        ("indomie", "instant noodles", "noodles"),
        WEST_AFRICAN_COUNTRIES,
        "convenience foods",
        "rice",
        "Profile excludes the flavouring sachet, which can add substantial sodium.",
    ),
    direct(
        "boiled_yam",
        "Nigerian yam, boiled",
        "02_035",
        ("boiled yam", "cooked yam", "yam"),
        ("Nigeria", "Ghana", "Benin", "Togo", "Côte d'Ivoire"),
        "roots, tubers and plantain",
        "staple",
    ),
    direct(
        "boiled_water_yam",
        "Water yam, boiled",
        "02_018",
        ("water yam", "boiled water yam"),
        ("Nigeria", "Ghana"),
        "roots, tubers and plantain",
        "staple",
    ),
    direct(
        "boiled_cocoyam",
        "Cocoyam, boiled",
        "02_006",
        ("cocoyam", "boiled cocoyam", "taro"),
        ("Nigeria", "Ghana", "Sierra Leone", "Liberia"),
        "roots, tubers and plantain",
        "staple",
    ),
    direct(
        "boiled_cassava",
        "Cassava, boiled",
        "02_003",
        ("boiled cassava", "cooked cassava"),
        WEST_AFRICAN_COUNTRIES,
        "roots, tubers and plantain",
        "staple",
    ),
    direct(
        "gari",
        "White gari, toasted fermented cassava granules",
        "02_039",
        ("gari", "garri", "dry gari", "dry garri"),
        ("Nigeria", "Ghana", "Sierra Leone", "Liberia", "Benin", "Togo"),
        "roots, tubers and plantain",
        "dry_staple",
    ),
    direct(
        "cassava_fufu",
        "Cassava fufu, fermented wet paste",
        "02_041",
        ("cassava fufu", "wet fufu", "foofoo"),
        ("Ghana", "Nigeria", "Sierra Leone", "Liberia", "Côte d'Ivoire", "Guinea"),
        "swallows and doughs",
        "swallow",
    ),
    direct(
        "boiled_ripe_plantain",
        "Ripe plantain, boiled",
        "02_057",
        ("boiled ripe plantain", "ripe boiled plantain"),
        WEST_AFRICAN_COUNTRIES,
        "roots, tubers and plantain",
        "staple",
    ),
    direct(
        "boiled_unripe_plantain",
        "Unripe plantain, boiled",
        "02_064",
        ("boiled unripe plantain", "green plantain", "unripe plantain"),
        WEST_AFRICAN_COUNTRIES,
        "roots, tubers and plantain",
        "staple",
    ),
    direct(
        "fried_plantain",
        "Plantain, deep fried",
        "02_084",
        ("fried plantain", "dodo", "alloco", "alokko"),
        ("Nigeria", "Ghana", "Côte d'Ivoire", "Benin", "Togo", "Guinea"),
        "roots, tubers and plantain",
        "staple",
    ),
    direct(
        "boiled_sweet_potato",
        "Sweet potato, boiled",
        "02_012",
        ("boiled sweet potato", "sweet potato"),
        WEST_AFRICAN_COUNTRIES,
        "roots, tubers and plantain",
        "staple",
    ),
    direct(
        "boiled_cowpeas",
        "Cowpeas / black-eyed beans, boiled",
        "03_007",
        ("boiled beans", "black eyed beans", "black-eyed beans", "cowpeas", "boiled cowpeas"),
        WEST_AFRICAN_COUNTRIES,
        "beans and pulses",
        "beans",
    ),
    direct(
        "boiled_bambara_groundnuts",
        "Bambara groundnuts, boiled",
        "03_012",
        ("bambara groundnuts", "bambara beans", "okpa beans"),
        ("Nigeria", "Ghana", "Burkina Faso", "Mali", "Benin", "Togo"),
        "beans and pulses",
        "beans",
    ),
    direct(
        "fermented_locust_bean",
        "Fermented African locust bean",
        "03_042",
        ("iru", "dawadawa", "soumbala", "netetu", "fermented locust bean"),
        WEST_AFRICAN_COUNTRIES,
        "condiments",
        "condiment",
    ),
    direct(
        "boiled_okra",
        "Okra, boiled",
        "04_042",
        ("boiled okra", "cooked okra"),
        WEST_AFRICAN_COUNTRIES,
        "vegetables and leaves",
        "vegetable",
    ),
    direct(
        "cooked_cassava_leaves",
        "Cassava leaves, boiled",
        "04_028",
        ("boiled cassava leaves", "cooked cassava leaves"),
        ("Sierra Leone", "Liberia", "Guinea", "Guinea-Bissau"),
        "vegetables and leaves",
        "vegetable",
    ),
    direct(
        "cooked_jute_mallow",
        "Jute mallow / bush okra leaves, boiled",
        "04_039",
        ("jute mallow", "bush okra leaves", "ewedu", "ayoyo"),
        ("Nigeria", "Ghana", "Togo", "Benin", "Burkina Faso"),
        "vegetables and leaves",
        "vegetable",
    ),
    direct(
        "cooked_spinach",
        "Spinach, boiled",
        "04_058",
        ("boiled spinach", "cooked spinach"),
        WEST_AFRICAN_COUNTRIES,
        "vegetables and leaves",
        "vegetable",
    ),
    direct(
        "cooked_amaranth",
        "Amaranth leaves, boiled",
        "04_024",
        ("amaranth leaves", "aleho", "green amaranth"),
        WEST_AFRICAN_COUNTRIES,
        "vegetables and leaves",
        "vegetable",
    ),
    direct(
        "cooked_waterleaf",
        "Waterleaf, boiled",
        "04_119",
        ("waterleaf", "cooked waterleaf"),
        ("Nigeria", "Ghana", "Sierra Leone", "Liberia"),
        "vegetables and leaves",
        "vegetable",
    ),
    direct(
        "cooked_pumpkin_leaves",
        "Pumpkin leaves, boiled",
        "04_054",
        ("pumpkin leaves", "ugu", "ugwu", "cooked ugu"),
        ("Nigeria", "Ghana", "Sierra Leone", "Liberia"),
        "vegetables and leaves",
        "vegetable",
    ),
    direct(
        "cooked_baobab_leaves",
        "Baobab leaves, boiled",
        "04_025",
        ("baobab leaves", "lalo leaves"),
        ("Senegal", "Mali", "Burkina Faso", "Niger", "Mauritania"),
        "vegetables and leaves",
        "vegetable",
    ),
    direct(
        "groundnut_paste",
        "Groundnut paste",
        "06_026",
        ("groundnut paste", "peanut paste", "natural peanut butter"),
        WEST_AFRICAN_COUNTRIES,
        "nuts and seeds",
        "condiment",
    ),
    direct(
        "egusi_seed",
        "Egusi / melon seed kernels, dried",
        "06_013",
        ("egusi seeds", "melon seeds", "ground egusi"),
        ("Nigeria", "Ghana", "Benin", "Togo", "Sierra Leone"),
        "nuts and seeds",
        "condiment",
    ),
    direct(
        "ogbono_seed",
        "Dikanut / ogbono kernels, dried",
        "06_008",
        ("ogbono seeds", "dikanut", "dika nut", "bush mango seeds"),
        ("Nigeria", "Ghana", "Sierra Leone", "Liberia"),
        "nuts and seeds",
        "condiment",
    ),
    direct(
        "stewed_beef",
        "Lean beef, stewed",
        "07_085",
        ("stewed beef", "beef", "beef pieces", "meat"),
        WEST_AFRICAN_COUNTRIES,
        "meat, fish and eggs",
        "protein",
    ),
    direct(
        "stewed_goat",
        "Lean goat meat, stewed",
        "07_115",
        ("stewed goat", "goat meat", "goat"),
        WEST_AFRICAN_COUNTRIES,
        "meat, fish and eggs",
        "protein",
    ),
    direct(
        "stewed_lamb",
        "Lean lamb / mutton, stewed",
        "07_128",
        ("stewed lamb", "stewed mutton", "mutton", "lamb"),
        WEST_AFRICAN_COUNTRIES,
        "meat, fish and eggs",
        "protein",
    ),
    direct(
        "stewed_chicken",
        "Chicken dark meat, stewed without skin",
        "07_102",
        ("stewed chicken", "chicken pieces", "chicken"),
        WEST_AFRICAN_COUNTRIES,
        "meat, fish and eggs",
        "protein",
    ),
    direct(
        "grilled_chicken",
        "Chicken dark meat, grilled without skin",
        "07_029",
        ("grilled chicken", "roast chicken"),
        WEST_AFRICAN_COUNTRIES,
        "meat, fish and eggs",
        "protein",
    ),
    direct(
        "boiled_egg",
        "Chicken egg, boiled",
        "08_002",
        ("boiled egg", "hard boiled egg"),
        WEST_AFRICAN_COUNTRIES,
        "meat, fish and eggs",
        "egg",
    ),
    direct(
        "fried_egg",
        "Chicken egg, fried in oil",
        "08_003",
        ("fried egg",),
        WEST_AFRICAN_COUNTRIES,
        "meat, fish and eggs",
        "egg",
    ),
    direct(
        "grilled_tilapia",
        "Tilapia fillet, grilled",
        "09_043",
        ("grilled tilapia", "tilapia"),
        WEST_AFRICAN_COUNTRIES,
        "meat, fish and eggs",
        "fish",
    ),
    direct(
        "grilled_mackerel",
        "Mackerel fillet, grilled",
        "09_025",
        ("grilled mackerel", "mackerel"),
        WEST_AFRICAN_COUNTRIES,
        "meat, fish and eggs",
        "fish",
    ),
    direct(
        "grilled_sardine",
        "Sardine fillet, grilled",
        "09_036",
        ("grilled sardines", "sardines", "sardine"),
        WEST_AFRICAN_COUNTRIES,
        "meat, fish and eggs",
        "fish",
    ),
    direct(
        "grilled_catfish",
        "Catfish fillet, grilled",
        "09_020",
        ("grilled catfish", "catfish"),
        ("Nigeria", "Ghana", "Sierra Leone", "Liberia", "Benin"),
        "meat, fish and eggs",
        "fish",
    ),
    direct(
        "dried_crayfish",
        "Dried whole crayfish",
        "09_057",
        ("dried crayfish", "ground crayfish", "crayfish"),
        ("Nigeria", "Ghana", "Sierra Leone", "Liberia"),
        "meat, fish and eggs",
        "condiment",
    ),
    direct(
        "coconut_milk",
        "Coconut milk",
        "06_006",
        ("coconut milk",),
        WEST_AFRICAN_COUNTRIES,
        "drinks and liquids",
        "drink",
    ),
    direct(
        "coconut_water",
        "Coconut water",
        "12_023",
        ("coconut water",),
        WEST_AFRICAN_COUNTRIES,
        "drinks and liquids",
        "drink",
    ),
    direct(
        "palm_wine",
        "Palm wine",
        "12_006",
        ("palm wine",),
        WEST_AFRICAN_COUNTRIES,
        "drinks and liquids",
        "drink",
    ),
    direct(
        "baobab_paste",
        "Sweet baobab paste",
        "05_056",
        ("baobab paste", "monkey bread paste"),
        ("Senegal", "Mali", "Burkina Faso", "Niger", "Mauritania"),
        "snacks and sweets",
        "snack",
    ),
    direct(
        "jollof_fonio",
        "Jollof fonio with fish and vegetables",
        "01_164",
        ("jollof fonio", "fonio jollof"),
        ("Burkina Faso", "Mali", "Guinea", "Senegal"),
        "rice and grain dishes",
        "rice",
    ),
    direct(
        "kedjenou",
        "Kedjenou, chicken and vegetable stew",
        "07_135",
        ("kedjenou", "kédjénou"),
        ("Côte d'Ivoire", "Burkina Faso"),
        "soups and stews",
        "stew",
        "WAFCT profile is a documented regional chicken-and-vegetable preparation.",
    ),
    direct(
        "babenda",
        "Babenda, leafy sauce with rice and groundnut",
        "14_021",
        ("babenda",),
        ("Burkina Faso",),
        "soups and stews",
        "stew",
    ),
)


RECIPES = (
    recipe(
        "pounded_yam",
        "Pounded yam (baseline)",
        ("pounded yam", "iyan"),
        ("Nigeria", "Ghana", "Benin", "Togo", "Côte d'Ivoire"),
        "swallows and doughs",
        "swallow",
        (("02_078", 1000, "boiled Nigerian yam"),),
        1000,
        "Pounding changes texture, while the final water content and wrap size vary by cook.",
    ),
    recipe(
        "amala",
        "Àmàlà from yam flour (baseline)",
        ("amala", "àmàlà", "yam flour swallow"),
        ("Nigeria",),
        "swallows and doughs",
        "swallow",
        (("02_036", 400, "white yam flour"),),
        1200,
        "Baseline assumes 400 g yam flour hydrated to 1.2 kg cooked àmàlà.",
    ),
    recipe(
        "eba",
        "Eba from gari (baseline)",
        ("eba", "ẹ̀bà", "garri swallow", "gari swallow"),
        ("Nigeria", "Ghana", "Benin", "Togo"),
        "swallows and doughs",
        "swallow",
        (("02_039", 400, "white gari"),),
        1200,
        "Baseline assumes 400 g gari hydrated to 1.2 kg cooked eba.",
    ),
    recipe(
        "banku",
        "Banku (baseline maize-cassava dough)",
        ("banku",),
        ("Ghana",),
        "swallows and doughs",
        "swallow",
        (
            ("01_099", 700, "cooked fermented maize dough"),
            ("02_041", 300, "fermented cassava paste"),
        ),
        1100,
        "Baseline uses a 70:30 cooked maize-to-cassava mixture; household fermentation and hydration vary.",
    ),
    recipe(
        "ghana_fufu",
        "Ghanaian cassava-plantain fufu (baseline)",
        ("ghana fufu", "ghanaian fufu", "plantain fufu", "cassava plantain fufu"),
        ("Ghana", "Côte d'Ivoire", "Guinea"),
        "swallows and doughs",
        "swallow",
        (
            ("02_041", 500, "fermented cassava paste"),
            ("02_058", 500, "cooked ripe plantain"),
        ),
        1000,
        "Baseline uses equal cooked weights of cassava and plantain; recipes differ by region and ripeness.",
    ),
    recipe(
        "attieke",
        "Attiéké, steamed cassava granules (hydrated baseline)",
        ("attieke", "attiéké", "acheke", "attiéké couscous"),
        ("Côte d'Ivoire", "Guinea", "Burkina Faso"),
        "swallows and doughs",
        "rice",
        (("02_039", 400, "fermented toasted cassava granules"),),
        1000,
        "WAFCT white gari is used as the closest regional fermented-cassava profile and hydrated to a cooked yield; validate against analysed attiéké data before clinical use.",
    ),
    recipe(
        "tuo_zaafi",
        "Tuo zaafi / maize-millet tuo (baseline)",
        ("tuo zaafi", "tz", "tuo", "saabo"),
        ("Ghana", "Burkina Faso", "Mali"),
        "swallows and doughs",
        "swallow",
        (
            ("01_105", 700, "stiff wholegrain maize porridge"),
            ("01_129", 300, "cooked pearl millet"),
        ),
        1000,
        "Baseline is a 70:30 cooked maize-to-millet dough; local grain ratios vary.",
    ),
    recipe(
        "jollof_rice",
        "Jollof rice (regional baseline)",
        ("jollof rice", "jollof", "party jollof", "nigerian jollof", "ghanaian jollof"),
        ("Nigeria", "Ghana", "Sierra Leone", "Liberia", "Gambia", "Senegal"),
        "rice and grain dishes",
        "rice",
        (
            ("01_134", 850, "cooked white rice"),
            ("04_124", 250, "cooked tomato"),
            ("04_112", 100, "cooked onion"),
            ("04_113", 80, "cooked red pepper"),
            ("11_004", 55, "red palm oil"),
            ("13_008", 8, "beef stock cube"),
        ),
        1200,
        "A transparent regional baseline; rice variety, oil, stock, meat and cooking loss vary substantially.",
    ),
    recipe(
        "fried_rice",
        "West African fried rice (baseline)",
        ("fried rice", "nigerian fried rice", "ghanaian fried rice"),
        ("Nigeria", "Ghana", "Sierra Leone", "Liberia"),
        "rice and grain dishes",
        "rice",
        (
            ("01_134", 850, "cooked white rice"),
            ("04_090", 100, "cooked cabbage"),
            ("04_091", 80, "cooked carrot"),
            ("04_088", 80, "cooked green beans"),
            ("04_112", 80, "cooked onion"),
            ("11_003", 60, "groundnut oil"),
            ("13_008", 8, "beef stock cube"),
        ),
        1150,
        "Baseline vegetable fried rice without a separate meat portion; oil and vegetable mix vary.",
    ),
    recipe(
        "rice_and_stew",
        "White rice with tomato stew and beef (baseline plate)",
        ("rice and stew", "white rice and stew", "rice with stew", "rice with tomato stew"),
        ("Nigeria", "Ghana", "Sierra Leone", "Liberia"),
        "rice and grain dishes",
        "plate",
        (
            ("01_134", 600, "cooked white rice"),
            ("04_124", 220, "cooked tomato"),
            ("04_112", 80, "cooked onion"),
            ("04_113", 70, "cooked red pepper"),
            ("11_004", 55, "red palm oil"),
            ("07_085", 250, "stewed lean beef"),
            ("13_008", 7, "beef stock cube"),
        ),
        1150,
        "Composite baseline includes beef; choose separate rice, stew and protein entries when you know their amounts.",
    ),
    recipe(
        "ofada_ayamase",
        "Ofada rice with ayamase stew (baseline)",
        ("ofada rice and ayamase", "ofada with ayamase", "ayamase", "designer stew"),
        ("Nigeria",),
        "rice and grain dishes",
        "plate",
        (
            ("01_136", 650, "cooked native red rice"),
            ("04_114", 250, "cooked green pepper"),
            ("04_112", 100, "cooked onion"),
            ("11_004", 100, "red palm oil"),
            ("07_085", 220, "stewed lean beef"),
            ("08_002", 100, "boiled egg"),
            ("03_042", 15, "fermented locust bean"),
            ("13_008", 8, "beef stock cube"),
        ),
        1250,
        "Baseline plate combines native red rice with a green-pepper palm-oil stew, beef and egg.",
    ),
    recipe(
        "waakye",
        "Waakye, rice and cowpeas (baseline)",
        ("waakye", "wakye", "rice and beans ghana"),
        ("Ghana",),
        "rice and grain dishes",
        "rice",
        (
            ("01_134", 650, "cooked white rice"),
            ("03_089", 350, "cooked cowpeas with cooking liquid"),
        ),
        1000,
        "Core rice-and-cowpea baseline; leaves, salt and accompaniments are not included.",
    ),
    recipe(
        "thieboudienne",
        "Thieboudienne / ceebu jën (baseline)",
        ("thieboudienne", "thieb", "ceebu jen", "ceebu jën", "thiebou dieune"),
        ("Senegal", "Mauritania", "Gambia"),
        "rice and grain dishes",
        "plate",
        (
            ("01_134", 800, "cooked white rice"),
            ("09_089", 350, "cooked tilapia"),
            ("04_124", 220, "cooked tomato"),
            ("04_112", 100, "cooked onion"),
            ("04_091", 120, "cooked carrot"),
            ("04_090", 120, "cooked cabbage"),
            ("11_003", 70, "groundnut oil"),
            ("13_008", 8, "beef stock cube"),
        ),
        1600,
        "Baseline rice, fish and vegetables; fish species, oil and vegetable mix vary by cook.",
    ),
    recipe(
        "benachin",
        "Benachin / one-pot jollof (baseline)",
        ("benachin", "benechin", "one pot rice", "gambian jollof"),
        ("Gambia", "Sierra Leone"),
        "rice and grain dishes",
        "plate",
        (
            ("01_134", 800, "cooked white rice"),
            ("07_102", 280, "stewed chicken"),
            ("04_124", 220, "cooked tomato"),
            ("04_112", 100, "cooked onion"),
            ("04_090", 100, "cooked cabbage"),
            ("11_003", 60, "groundnut oil"),
            ("13_008", 8, "beef stock cube"),
        ),
        1450,
        "Baseline Gambian one-pot rice with chicken and vegetables.",
    ),
    recipe(
        "riz_gras",
        "Riz gras (baseline)",
        ("riz gras", "fat rice"),
        ("Burkina Faso", "Mali", "Niger", "Togo", "Benin"),
        "rice and grain dishes",
        "plate",
        (
            ("01_134", 800, "cooked white rice"),
            ("07_085", 250, "stewed beef"),
            ("04_124", 220, "cooked tomato"),
            ("04_112", 100, "cooked onion"),
            ("11_003", 70, "groundnut oil"),
            ("13_008", 8, "beef stock cube"),
        ),
        1350,
        "Baseline tomato rice with beef and oil; regional recipes vary.",
    ),
    recipe(
        "cachupa",
        "Cachupa (baseline)",
        ("cachupa", "cachupa rica", "cachupa guisada"),
        ("Cabo Verde",),
        "rice and grain dishes",
        "stew",
        (
            ("01_104", 350, "cooked white maize"),
            ("03_089", 300, "cooked cowpeas"),
            ("02_070", 180, "cooked sweet potato"),
            ("02_051", 180, "cooked cassava"),
            ("07_102", 250, "stewed chicken"),
            ("04_090", 180, "cooked cabbage"),
            ("04_112", 80, "cooked onion"),
            ("11_003", 40, "groundnut oil"),
        ),
        1600,
        "Baseline slow-cooked maize, beans, roots, cabbage and chicken; cachupa varies by island and household.",
    ),
    recipe(
        "dambou",
        "Dambou, millet with greens (baseline)",
        ("dambou", "dambo"),
        ("Niger",),
        "rice and grain dishes",
        "rice",
        (
            ("01_129", 650, "cooked pearl millet"),
            ("04_133", 300, "cooked green leafy vegetables"),
            ("11_003", 45, "groundnut oil"),
            ("04_112", 70, "cooked onion"),
        ),
        1000,
        "Baseline millet-and-greens preparation; couscous grain and leaf choices vary.",
    ),
    recipe(
        "djenkoume",
        "Djenkoume / maize dough with tomato (baseline)",
        ("djenkoume", "djinkoume"),
        ("Togo", "Benin"),
        "rice and grain dishes",
        "swallow",
        (
            ("01_105", 700, "stiff maize porridge"),
            ("04_124", 220, "cooked tomato"),
            ("04_112", 80, "cooked onion"),
            ("11_004", 50, "red palm oil"),
        ),
        1000,
        "Baseline cooked maize dough enriched with tomato, onion and palm oil.",
    ),
    recipe(
        "egusi_soup",
        "Egusi soup (baseline recipe)",
        ("egusi soup", "egusi", "melon seed soup"),
        ("Nigeria", "Ghana", "Benin", "Togo", "Sierra Leone"),
        "soups and stews",
        "soup",
        (
            ("06_013", 250, "melon seed kernels"),
            ("11_004", 110, "red palm oil"),
            ("04_118", 450, "cooked spinach"),
            ("07_085", 260, "stewed lean beef"),
            ("09_057", 30, "dried crayfish"),
            ("04_124", 220, "cooked tomato"),
            ("04_112", 100, "cooked onion"),
            ("04_046", 25, "fresh chilli"),
            ("13_008", 8, "beef stock cube"),
        ),
        1650,
        "NutriRoot baseline with egusi, palm oil, greens, beef and crayfish; seed, oil and protein ratios vary widely.",
    ),
    recipe(
        "ogbono_soup",
        "Ogbono soup (baseline recipe)",
        ("ogbono soup", "ogbono", "draw soup", "dika soup"),
        ("Nigeria", "Ghana", "Sierra Leone", "Liberia"),
        "soups and stews",
        "soup",
        (
            ("06_008", 180, "dikanut kernels"),
            ("11_004", 100, "red palm oil"),
            ("04_118", 350, "cooked spinach"),
            ("07_085", 260, "stewed lean beef"),
            ("09_057", 30, "dried crayfish"),
            ("04_112", 100, "cooked onion"),
            ("04_046", 20, "fresh chilli"),
            ("13_008", 8, "beef stock cube"),
        ),
        1600,
        "NutriRoot baseline with dikanut, palm oil, greens, beef and crayfish.",
    ),
    recipe(
        "okra_soup",
        "West African okra soup (baseline)",
        ("okra soup", "okro soup", "okra stew", "okro stew"),
        ("Nigeria", "Ghana", "Sierra Leone", "Liberia", "Gambia", "Benin", "Togo"),
        "soups and stews",
        "soup",
        (
            ("04_111", 650, "cooked okra"),
            ("11_004", 80, "red palm oil"),
            ("09_089", 300, "cooked tilapia"),
            ("09_057", 25, "dried crayfish"),
            ("04_112", 100, "cooked onion"),
            ("04_046", 20, "fresh chilli"),
            ("13_008", 7, "beef stock cube"),
        ),
        1500,
        "Baseline fish-and-okra soup; meat, fish, oil and leaf additions vary by household.",
    ),
    recipe(
        "efo_riro",
        "Efo riro (baseline recipe)",
        ("efo riro", "vegetable soup yoruba", "spinach stew"),
        ("Nigeria",),
        "soups and stews",
        "soup",
        (
            ("04_118", 800, "cooked spinach"),
            ("11_004", 120, "red palm oil"),
            ("07_085", 300, "stewed lean beef"),
            ("09_057", 30, "dried crayfish"),
            ("04_113", 220, "cooked red pepper"),
            ("04_112", 100, "cooked onion"),
            ("03_042", 15, "fermented locust bean"),
            ("13_008", 7, "beef stock cube"),
        ),
        1550,
        "Baseline uses spinach as the available WAFCT leafy-green profile; traditional leaf choice and oil vary.",
    ),
    recipe(
        "edikang_ikong",
        "Edikang ikong (baseline recipe)",
        ("edikang ikong", "edikangikong", "edikang ikong soup"),
        ("Nigeria",),
        "soups and stews",
        "soup",
        (
            ("04_116", 500, "cooked pumpkin leaves"),
            ("04_120", 500, "cooked waterleaf"),
            ("11_004", 100, "red palm oil"),
            ("07_085", 250, "stewed lean beef"),
            ("09_057", 35, "dried crayfish"),
            ("04_112", 80, "cooked onion"),
            ("13_008", 7, "beef stock cube"),
        ),
        1500,
        "Baseline models the characteristic pumpkin-leaf and waterleaf combination with beef and crayfish.",
    ),
    recipe(
        "afang_soup",
        "Afang soup (green-leaf baseline)",
        ("afang soup", "afang"),
        ("Nigeria",),
        "soups and stews",
        "soup",
        (
            ("04_133", 450, "cooked regional green-leaf average"),
            ("04_120", 450, "cooked waterleaf"),
            ("11_004", 110, "red palm oil"),
            ("07_085", 260, "stewed lean beef"),
            ("09_057", 35, "dried crayfish"),
            ("13_008", 7, "beef stock cube"),
        ),
        1450,
        "WAFCT green-leaf average is a disclosed proxy for afang leaves; replace when a validated afang profile is available.",
    ),
    recipe(
        "bitterleaf_soup",
        "Bitterleaf soup (baseline recipe)",
        ("bitterleaf soup", "bitter leaf soup", "ofe onugbu"),
        ("Nigeria",),
        "soups and stews",
        "soup",
        (
            ("04_126", 500, "cooked bitter vernonia leaves"),
            ("11_004", 110, "red palm oil"),
            ("07_085", 270, "stewed lean beef"),
            ("09_057", 30, "dried crayfish"),
            ("06_026", 80, "groundnut paste"),
            ("13_008", 7, "beef stock cube"),
        ),
        1450,
        "Baseline bitterleaf soup with palm oil, beef, crayfish and a small groundnut thickener.",
    ),
    recipe(
        "banga_soup",
        "Banga / palm-nut soup (baseline)",
        ("banga soup", "palm nut soup", "palmnut soup", "abenkwan"),
        ("Nigeria", "Ghana"),
        "soups and stews",
        "soup",
        (
            ("14_023", 1100, "WAFCT palm-fruit sauce with fish and vegetables"),
            ("07_085", 250, "stewed lean beef"),
            ("04_046", 20, "fresh chilli"),
        ),
        1370,
        "Uses WAFCT palm-fruit sauce as the source-backed base, with added beef.",
    ),
    recipe(
        "light_soup",
        "Ghanaian light soup (baseline)",
        ("light soup", "ghana light soup", "goat light soup"),
        ("Ghana",),
        "soups and stews",
        "soup",
        (
            ("07_115", 350, "stewed lean goat"),
            ("04_124", 300, "cooked tomato"),
            ("04_112", 120, "cooked onion"),
            ("04_046", 25, "fresh chilli"),
            ("13_008", 7, "beef stock cube"),
        ),
        1700,
        "Broth-rich baseline; final water volume, goat cut and seasoning drive most variation.",
    ),
    recipe(
        "pepper_soup",
        "Nigerian pepper soup (goat and catfish baseline)",
        ("pepper soup", "goat pepper soup", "catfish pepper soup", "point and kill"),
        ("Nigeria", "Ghana", "Sierra Leone", "Liberia"),
        "soups and stews",
        "soup",
        (
            ("07_115", 300, "stewed lean goat"),
            ("09_020", 250, "grilled catfish profile"),
            ("04_112", 100, "cooked onion"),
            ("04_046", 25, "fresh chilli"),
            ("13_026", 8, "uda spice"),
            ("13_008", 7, "beef stock cube"),
        ),
        1750,
        "Baseline combines goat and catfish in a water-rich broth; users should log a single protein separately when known.",
    ),
    recipe(
        "groundnut_stew",
        "Groundnut stew / maafe (regional baseline)",
        ("groundnut stew", "groundnut soup", "peanut stew", "peanut soup", "maafe", "mafé", "domoda", "tigadegena", "caldo de mancarra"),
        ("Gambia", "Senegal", "Mali", "Guinea", "Guinea-Bissau", "Sierra Leone", "Ghana"),
        "soups and stews",
        "stew",
        (
            ("06_026", 260, "groundnut paste"),
            ("04_124", 260, "cooked tomato"),
            ("04_112", 120, "cooked onion"),
            ("07_102", 320, "stewed chicken"),
            ("11_003", 45, "groundnut oil"),
            ("04_046", 20, "fresh chilli"),
            ("13_008", 8, "beef stock cube"),
        ),
        1650,
        "Shared groundnut-and-tomato baseline; maafe, domoda and caldo de mancarra have distinct local recipes.",
    ),
    recipe(
        "cassava_leaf_stew",
        "Cassava-leaf stew (baseline)",
        ("cassava leaf stew", "cassava leaves stew", "cassava leaf soup", "saka saka"),
        ("Sierra Leone", "Liberia", "Guinea", "Guinea-Bissau"),
        "soups and stews",
        "stew",
        (
            ("04_092", 750, "cooked cassava leaves"),
            ("11_004", 100, "red palm oil"),
            ("06_026", 100, "groundnut paste"),
            ("07_085", 260, "stewed lean beef"),
            ("09_057", 30, "dried crayfish"),
            ("04_112", 100, "cooked onion"),
            ("13_008", 7, "beef stock cube"),
        ),
        1550,
        "Baseline leaf stew with palm oil, groundnut, beef and dried seafood.",
    ),
    recipe(
        "plasas",
        "Plasas / leafy stew (baseline)",
        ("plasas", "plassas", "palaver sauce"),
        ("Sierra Leone", "Liberia", "Gambia"),
        "soups and stews",
        "stew",
        (
            ("04_107", 700, "cooked jute mallow"),
            ("11_004", 100, "red palm oil"),
            ("06_026", 100, "groundnut paste"),
            ("09_089", 280, "cooked tilapia"),
            ("04_112", 100, "cooked onion"),
            ("13_008", 7, "beef stock cube"),
        ),
        1500,
        "Baseline uses jute mallow as the leafy profile; plasas may use potato greens, cassava leaves or other leaves.",
    ),
    recipe(
        "potato_greens",
        "Sweet-potato greens stew (baseline)",
        ("potato greens", "potato greens stew", "sweet potato leaf stew"),
        ("Liberia", "Sierra Leone"),
        "soups and stews",
        "stew",
        (
            ("04_121", 750, "cooked sweet-potato leaves"),
            ("11_004", 100, "red palm oil"),
            ("07_085", 270, "stewed lean beef"),
            ("09_057", 30, "dried crayfish"),
            ("04_112", 100, "cooked onion"),
            ("13_008", 7, "beef stock cube"),
        ),
        1500,
        "Baseline Liberian/Sierra Leonean sweet-potato-leaf stew.",
    ),
    recipe(
        "kontomire_stew",
        "Kontomire stew (baseline)",
        ("kontomire stew", "palava sauce ghana", "cocoyam leaf stew"),
        ("Ghana",),
        "soups and stews",
        "stew",
        (
            ("04_097", 700, "cooked cocoyam leaves"),
            ("11_004", 90, "red palm oil"),
            ("04_124", 220, "cooked tomato"),
            ("04_112", 100, "cooked onion"),
            ("09_089", 250, "cooked tilapia"),
            ("08_002", 100, "boiled egg"),
            ("13_008", 7, "beef stock cube"),
        ),
        1450,
        "Baseline cocoyam-leaf stew with fish and egg.",
    ),
    recipe(
        "palm_butter_soup",
        "Palm-butter soup / sauce graine (baseline)",
        ("palm butter soup", "palm butter", "sauce graine", "palm fruit soup"),
        ("Liberia", "Sierra Leone", "Côte d'Ivoire", "Guinea"),
        "soups and stews",
        "soup",
        (
            ("14_023", 1100, "WAFCT palm-fruit sauce with fish and vegetables"),
            ("07_102", 280, "stewed chicken"),
            ("04_046", 20, "fresh chilli"),
        ),
        1400,
        "Uses WAFCT palm-fruit sauce as the source-backed base, with added chicken.",
    ),
    recipe(
        "red_red",
        "Red red, Ghanaian bean stew (baseline)",
        ("red red", "ghanaian red red", "bean stew ghana"),
        ("Ghana",),
        "beans and pulses",
        "beans",
        (
            ("03_089", 800, "cooked cowpeas"),
            ("04_124", 240, "cooked tomato"),
            ("04_112", 100, "cooked onion"),
            ("11_004", 90, "red palm oil"),
            ("04_046", 15, "fresh chilli"),
            ("13_008", 6, "beef stock cube"),
        ),
        1200,
        "Baseline bean stew only; fried plantain should be logged separately.",
    ),
    recipe(
        "beans_porridge",
        "Nigerian beans porridge (baseline)",
        ("beans porridge", "bean porridge", "ewa riro", "stewed beans"),
        ("Nigeria",),
        "beans and pulses",
        "beans",
        (
            ("03_089", 850, "cooked cowpeas"),
            ("04_124", 220, "cooked tomato"),
            ("04_112", 100, "cooked onion"),
            ("11_004", 70, "red palm oil"),
            ("04_046", 15, "fresh chilli"),
            ("13_008", 6, "beef stock cube"),
        ),
        1250,
        "Baseline Nigerian cowpea porridge; yam, plantain, fish and extra oil are not included.",
    ),
    recipe(
        "moi_moi",
        "Moi moi / moin moin (baseline)",
        ("moi moi", "moin moin", "moimoi", "steamed bean pudding", "alele"),
        ("Nigeria", "Benin", "Ghana"),
        "beans and pulses",
        "snack",
        (
            ("03_101", 750, "cooked dehulled cowpeas"),
            ("11_004", 70, "red palm oil"),
            ("04_113", 120, "cooked red pepper"),
            ("04_112", 80, "cooked onion"),
            ("13_008", 6, "beef stock cube"),
        ),
        1050,
        "Baseline steamed bean pudding without egg or fish fillings.",
    ),
    recipe(
        "akara",
        "Akara / koose (baseline)",
        ("akara", "acaraje", "acarajé", "koose", "bean cakes", "bean fritters"),
        ("Nigeria", "Ghana", "Benin", "Togo", "Sierra Leone"),
        "beans and pulses",
        "snack",
        (
            ("03_101", 650, "cooked dehulled cowpea profile"),
            ("11_003", 110, "absorbed groundnut oil"),
            ("04_112", 80, "cooked onion"),
            ("04_046", 15, "fresh chilli"),
        ),
        800,
        "Baseline models cooked cowpea batter plus absorbed frying oil; real oil absorption varies.",
    ),
    recipe(
        "asaro",
        "Asaro / yam porridge (baseline)",
        ("asaro", "yam porridge", "yam pottage"),
        ("Nigeria",),
        "roots, tubers and plantain",
        "stew",
        (
            ("02_078", 850, "cooked Nigerian yam"),
            ("04_124", 220, "cooked tomato"),
            ("04_112", 100, "cooked onion"),
            ("11_004", 70, "red palm oil"),
            ("04_118", 180, "cooked spinach"),
            ("13_008", 6, "beef stock cube"),
        ),
        1300,
        "Baseline yam porridge with tomato, palm oil and greens.",
    ),
    recipe(
        "ukwa",
        "Ukwa / African breadfruit porridge (baseline)",
        ("ukwa", "african breadfruit porridge", "breadfruit porridge"),
        ("Nigeria",),
        "beans and pulses",
        "beans",
        (
            ("06_031", 350, "dried African breadfruit seeds"),
            ("11_004", 35, "red palm oil"),
        ),
        1050,
        "Baseline assumes dried breadfruit seeds cooked with water and a small amount of palm oil.",
    ),
    recipe(
        "abacha",
        "Abacha / African salad (cassava baseline)",
        ("abacha", "african salad", "cassava salad"),
        ("Nigeria",),
        "roots, tubers and plantain",
        "staple",
        (
            ("02_039", 350, "fermented cassava granules"),
            ("11_004", 80, "red palm oil"),
            ("09_057", 30, "dried crayfish"),
            ("04_112", 100, "cooked onion"),
            ("04_046", 15, "fresh chilli"),
        ),
        800,
        "WAFCT gari is a disclosed proxy for prepared abacha; hydration and cassava processing differ.",
    ),
    recipe(
        "suya",
        "Beef suya (baseline)",
        ("suya", "beef suya", "soya kebab", "spiced beef skewer"),
        ("Nigeria", "Ghana", "Niger"),
        "meat, fish and eggs",
        "skewer",
        (
            ("07_011", 850, "grilled lean beef"),
            ("06_026", 80, "groundnut paste proxy for kuli-kuli spice"),
            ("13_006", 12, "dried chilli"),
            ("04_112", 50, "cooked onion"),
        ),
        950,
        "Baseline uses grilled lean beef and groundnut-rich spice; cut, oil and yaji blend vary.",
    ),
    recipe(
        "chicken_yassa",
        "Chicken yassa (baseline)",
        ("chicken yassa", "yassa chicken", "poulet yassa", "yassa"),
        ("Senegal", "Gambia", "Guinea", "Mali"),
        "soups and stews",
        "stew",
        (
            ("07_102", 700, "stewed chicken"),
            ("04_112", 550, "cooked onion"),
            ("13_013", 60, "prepared mustard"),
            ("11_003", 60, "groundnut oil"),
            ("04_046", 15, "fresh chilli"),
        ),
        1250,
        "Onion-forward chicken baseline; lemon juice is omitted because it contributes little to the nutrients tracked here.",
    ),
    recipe(
        "kelewele",
        "Kelewele, spiced fried plantain (baseline)",
        ("kelewele", "spiced fried plantain"),
        ("Ghana",),
        "snacks and sweets",
        "staple",
        (
            ("02_084", 900, "fried plantain"),
            ("04_082", 25, "fresh ginger"),
            ("13_006", 5, "dried chilli"),
        ),
        930,
        "Uses the WAFCT fried-plantain profile plus ginger and chilli; frying-oil uptake varies.",
    ),
    recipe(
        "shito",
        "Shito, Ghanaian black pepper sauce (baseline)",
        ("shito", "black pepper sauce ghana", "ghanaian shito"),
        ("Ghana",),
        "condiments",
        "condiment",
        (
            ("09_057", 100, "dried crayfish"),
            ("11_004", 300, "red palm oil"),
            ("04_124", 180, "cooked tomato"),
            ("04_112", 150, "cooked onion"),
            ("13_006", 35, "dried chilli"),
        ),
        700,
        "Baseline dried-seafood pepper sauce; oil and seafood content vary considerably.",
    ),
    recipe(
        "puff_puff",
        "Puff puff / bofrot (baseline)",
        ("puff puff", "puff-puff", "bofrot", "boflot", "mikate"),
        ("Nigeria", "Ghana", "Sierra Leone", "Liberia"),
        "snacks and sweets",
        "snack",
        (
            ("01_089", 400, "fortified Nigerian wheat flour"),
            ("13_002", 100, "white sugar"),
            ("11_003", 80, "absorbed groundnut oil"),
        ),
        850,
        "Baseline fried sweet dough; water yield and frying-oil absorption are assumptions.",
    ),
    recipe(
        "chin_chin",
        "Chin chin (baseline)",
        ("chin chin", "chin-chin"),
        ("Nigeria", "Ghana", "Sierra Leone"),
        "snacks and sweets",
        "snack",
        (
            ("01_089", 500, "fortified Nigerian wheat flour"),
            ("13_002", 130, "white sugar"),
            ("11_003", 130, "groundnut oil and absorbed frying oil"),
        ),
        760,
        "Baseline flour, sugar and oil model; milk, egg and exact oil uptake are omitted.",
    ),
    recipe(
        "meat_pie",
        "West African meat pie (baseline)",
        ("nigerian meat pie", "ghana meat pie", "meat pie"),
        ("Nigeria", "Ghana", "Sierra Leone", "Liberia"),
        "snacks and sweets",
        "snack",
        (
            ("01_089", 420, "fortified Nigerian wheat flour"),
            ("07_085", 260, "stewed lean beef"),
            ("11_003", 120, "groundnut oil proxy for pastry fat"),
            ("04_112", 80, "cooked onion"),
            ("04_091", 80, "cooked carrot"),
        ),
        900,
        "Baseline pastry-and-beef model; butter/margarine, potato and pastry thickness vary.",
    ),
)
